### ISSUE TITLE
`Failed to authenticate` on login

### ISSUE THREAD

**Issue by filcuk** [LouisHDev/planka_app#1] opened 2024-10-04 10:11 UTC
I get this error when attempting to login.
Using a domain (via cloudflare) - have tried with & without `https://`
The error is immediate - as soon as I press the `login` button. 

Not sure if this is expected at this stage! 
If not and some details would be useful, please let me know if I can dig into some logs.
I see no logs on planka itself when this fails

**Comment by drascom** [comment] 2024-10-04 22:31
same here. cant login The error is immediate - as soon as I press the login button.

**Comment by GarandPLG** [comment] 2024-10-06 22:14
the same problem. I installed the application through Obtainium, I use Cloudflare and Nginx Proxy Manager to serve my instance of Planka. I'm using [docker-compose.yaml](https://www.youtube.com/watch?v=rsyU2cBbbSI)

**Comment by LouisHDev** [comment] 2024-10-06 22:23
Thanks alot! Hang in, working on it!

**Comment by LouisHDev** [comment] 2024-10-07 08:55
Here is the url construction:

Uri.parse('https://$domain/api/access-tokens');

I've added further error logging, so we can identify the problem in v0.0.6 :)

**Comment by LouisHDev** [comment] 2024-10-07 09:01
https://github.com/LouisHDev/planka_app/releases/tag/v0.0.6

**Comment by GarandPLG** [comment] 2024-10-07 09:45
![Screenshot_20241007_114251](https://github.com/user-attachments/assets/36a21181-3ab2-4b38-8e4e-4b8ed1d16a53)
![Screenshot_20241007_114235](https://github.com/user-attachments/assets/f8fa3a14-959f-4750-87f6-223c06d689cf)

**Comment by LouisHDev** [comment] 2024-10-07 10:07
Might there be a whitespace after the "planka.garandplg.com" ? @GarandPLG 

Edit: never mind, would show a completely different error

**Comment by GarandPLG** [comment] 2024-10-07 10:14
@LouisHDev There is something more i can do? More data to provide?

**Comment by LouisHDev** [comment] 2024-10-07 10:16
Would be awesome if you can share credentials via mail for example, so i can look into it more. Make a text account maybe? :) With my domains, everything works fine... @GarandPLG

**Comment by GarandPLG** [comment] 2024-10-07 10:23
@LouisHDev give me a moment

**Comment by GarandPLG** [comment] 2024-10-07 11:01
@LouisHDev ok so on what email i can share testuser credentials?

**Comment by LouisHDev** [comment] 2024-10-07 12:18
@GarandPLG louis@bbsl.de

And what Planka Version are you using?

**Comment by GarandPLG** [comment] 2024-10-07 13:04
@LouisHDev I sent an email using tutanota, so I need to add a password to the email. The password is: 123rdf__a

**Comment by LouisHDev** [comment] 2024-10-07 13:30
<img width="562" alt="Bildschirmfoto 2024-10-07 um 15 29 31" src="https://github.com/user-attachments/assets/412578d0-03f0-4832-bf7b-c26266cf095a">

Now im confused, works without any issues for me... @GarandPLG 

The reason must be a typo of some sort, or blank space or something.

**Comment by LouisHDev** [comment] 2024-10-07 13:31
i just used "planka.garandplg.com"

**Comment by GarandPLG** [comment] 2024-10-07 13:47
I'm 100% sure I've spelled `Server Address` correctly. Maybe the issue is with lack of privileges? Or Obtainium isn't a good way to install Planka mobile app. I would try to install it manually.  

Edit: Nope, still no luck

**Comment by GarandPLG** [comment] 2024-10-07 14:01
maybe debug/development version have something, that official release didn't have? Classical "It works on my machine" problem

**Comment by LouisHDev** [comment] 2024-10-07 14:13
Could finally reproduce the error myself, fixing it rn! Thanks alot for your help! @GarandPLG

**Comment by LouisHDev** [comment] 2024-10-07 14:28
Will be fixed shortly in v0.0.7.

**Comment by GarandPLG** [comment] 2024-10-07 14:55
@LouisHDev what was the issue?

**Comment by filcuk** [comment] 2024-10-08 17:55
Only just got to the messages - thanks for the fix!
@GarandPLG you can check the commit 04e2fa96d44d34d17302c43c8f711f9f5d1f4a57
Looks like it needed an internet permission? Possible due to different android versions, the permissions can be a mess.

**Comment by drascom** [comment] 2024-10-08 23:41
it same for me with new version i downloaded apk from github directly.

**Comment by LouisHDev** [comment] 2024-10-10 11:13
> @LouisHDev what was the issue?

It was an internet access issue.

**Comment by LouisHDev** [comment] 2024-10-10 11:15
> it same for me with new version i downloaded apk from github directly.

Hi, it should be fixed. Make sure that you have no "https://" infront of your domain. Just the pure domain name. Also make sure you do not have any whitespaces.

**Comment by LouisHDev** [comment] 2024-10-10 11:28
Update: in v0.0.8 any whitespaces aswell as "https://" will be cut out automatically. There will now also be a hint inside the "Server Adress" field.

**Comment by sankalp15** [comment] 2024-10-14 18:58
I installed app in Truenas but it is http and not https. app fails to authenticate in such case

**Comment by LouisHDev** [comment] 2024-10-16 11:08
Thanks, working on it.

**Comment by LouisHDev** [comment] 2024-10-16 15:43
Fixed, you will now be able to select "http", "https" or "localhost" in new v0.0.8 :)

**Closed as completed by LouisHDev** 2024-10-16 15:43 UTC
Labels: bug
